// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4lTXuzY3MYNs3ArsUpNveyunZsSgu4fY',
    appId: '1:909586382430:web:7132f78fc73cd36e94becf',
    messagingSenderId: '909586382430',
    projectId: 'event-management-app-147d4',
    authDomain: 'event-management-app-147d4.firebaseapp.com',
    storageBucket: 'event-management-app-147d4.firebasestorage.app',
    measurementId: 'G-BDXYCMWQTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUAKY1XtGgrPBea2UswnNacEcTof1prYc',
    appId: '1:909586382430:android:af7b4277b843267c94becf',
    messagingSenderId: '909586382430',
    projectId: 'event-management-app-147d4',
    storageBucket: 'event-management-app-147d4.firebasestorage.app',
  );
}
